######################################################################
# Automatically generated by qmake (2.01a) ? 11? 10 11:22:37 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += stringlistmodel.h
SOURCES += main.cpp stringlistmodel.cpp
