######################################################################
# Automatically generated by qmake (2.01a) ? 11? 9 10:32:22 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += quit.cpp
