######################################################################
# Automatically generated by qmake (2.01a) ? 7 4 22:45:41 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += age.cpp
