######################################################################
# Automatically generated by qmake (2.01a) ? 11? 10 10:00:32 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
