######################################################################
# Automatically generated by qmake (2.01a) ? 11? 27 17:28:12 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += test.h thread.h ticker.h
SOURCES += main.cpp test.cpp thread.cpp ticker.cpp
