######################################################################
# Automatically generated by qmake (2.01a) ? 7 4 21:34:19 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += test.cpp
