/*
 * Internal module API header file.
 *
 * Generated by SIP 4.9.1-snapshot-20091015 on Mon Nov 16 19:36:49 2009
 */

#ifndef _libserialAPI_H
#define _libserialAPI_H


#include <sip.h>

/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_SerialPort__UnsupportedBaudRate 0
#define sipName_SerialPort__UnsupportedBaudRate &sipStrings_libserial[0]
#define sipNameNr_32 32
#define sipName_32 &sipStrings_libserial[32]
#define sipNameNr_59 59
#define sipName_59 &sipStrings_libserial[59]
#define sipNameNr_SerialPort__CharacterSize 85
#define sipName_SerialPort__CharacterSize &sipStrings_libserial[85]
#define sipNameNr_SerialPort__ReadTimeout 111
#define sipName_SerialPort__ReadTimeout &sipStrings_libserial[111]
#define sipNameNr_SerialPort__AlreadyOpen 135
#define sipName_SerialPort__AlreadyOpen &sipStrings_libserial[135]
#define sipNameNr_SerialPort__FlowControl 159
#define sipName_SerialPort__FlowControl &sipStrings_libserial[159]
#define sipNameNr_SerialPort__OpenFailed 183
#define sipName_SerialPort__OpenFailed &sipStrings_libserial[183]
#define sipNameNr_std__invalid_argument 206
#define sipName_std__invalid_argument &sipStrings_libserial[206]
#define sipNameNr_FLOW_CONTROL_DEFAULT 228
#define sipName_FLOW_CONTROL_DEFAULT &sipStrings_libserial[228]
#define sipNameNr_SerialPort__StopBits 249
#define sipName_SerialPort__StopBits &sipStrings_libserial[249]
#define sipNameNr_SerialPort__BaudRate 270
#define sipName_SerialPort__BaudRate &sipStrings_libserial[270]
#define sipNameNr_291 291
#define sipName_291 &sipStrings_libserial[291]
#define sipNameNr_UnsupportedBaudRate 12
#define sipName_UnsupportedBaudRate &sipStrings_libserial[12]
#define sipNameNr_SerialPort__NotOpen 311
#define sipName_SerialPort__NotOpen &sipStrings_libserial[311]
#define sipNameNr_SerialPort__Parity 331
#define sipName_SerialPort__Parity &sipStrings_libserial[331]
#define sipNameNr_std__runtime_error 350
#define sipName_std__runtime_error &sipStrings_libserial[350]
#define sipNameNr_FLOW_CONTROL_NONE 369
#define sipName_FLOW_CONTROL_NONE &sipStrings_libserial[369]
#define sipNameNr_FLOW_CONTROL_HARD 387
#define sipName_FLOW_CONTROL_HARD &sipStrings_libserial[387]
#define sipNameNr_STOP_BITS_DEFAULT 405
#define sipName_STOP_BITS_DEFAULT &sipStrings_libserial[405]
#define sipNameNr_CHAR_SIZE_DEFAULT 423
#define sipName_CHAR_SIZE_DEFAULT &sipStrings_libserial[423]
#define sipNameNr_441 441
#define sipName_441 &sipStrings_libserial[441]
#define sipNameNr_GetNumOfStopBits 458
#define sipName_GetNumOfStopBits &sipStrings_libserial[458]
#define sipNameNr_SetNumOfStopBits 475
#define sipName_SetNumOfStopBits &sipStrings_libserial[475]
#define sipNameNr_invalid_argument 211
#define sipName_invalid_argument &sipStrings_libserial[211]
#define sipNameNr_std__logic_error 492
#define sipName_std__logic_error &sipStrings_libserial[492]
#define sipNameNr_IsDataAvailable 509
#define sipName_IsDataAvailable &sipStrings_libserial[509]
#define sipNameNr_GetFlowControl 525
#define sipName_GetFlowControl &sipStrings_libserial[525]
#define sipNameNr_SetFlowControl 540
#define sipName_SetFlowControl &sipStrings_libserial[540]
#define sipNameNr_PARITY_DEFAULT 555
#define sipName_PARITY_DEFAULT &sipStrings_libserial[555]
#define sipNameNr_std__exception 570
#define sipName_std__exception &sipStrings_libserial[570]
#define sipNameNr_CharacterSize 97
#define sipName_CharacterSize &sipStrings_libserial[97]
#define sipNameNr_runtime_error 355
#define sipName_runtime_error &sipStrings_libserial[355]
#define sipNameNr_BAUD_DEFAULT 585
#define sipName_BAUD_DEFAULT &sipStrings_libserial[585]
#define sipNameNr_GetCharSize 598
#define sipName_GetCharSize &sipStrings_libserial[598]
#define sipNameNr_SetCharSize 610
#define sipName_SetCharSize &sipStrings_libserial[610]
#define sipNameNr_GetBaudRate 622
#define sipName_GetBaudRate &sipStrings_libserial[622]
#define sipNameNr_SetBaudRate 634
#define sipName_SetBaudRate &sipStrings_libserial[634]
#define sipNameNr_ReadTimeout 123
#define sipName_ReadTimeout &sipStrings_libserial[123]
#define sipNameNr_AlreadyOpen 147
#define sipName_AlreadyOpen &sipStrings_libserial[147]
#define sipNameNr_FlowControl 171
#define sipName_FlowControl &sipStrings_libserial[171]
#define sipNameNr_PARITY_NONE 646
#define sipName_PARITY_NONE &sipStrings_libserial[646]
#define sipNameNr_PARITY_EVEN 658
#define sipName_PARITY_EVEN &sipStrings_libserial[658]
#define sipNameNr_STOP_BITS_2 670
#define sipName_STOP_BITS_2 &sipStrings_libserial[670]
#define sipNameNr_STOP_BITS_1 682
#define sipName_STOP_BITS_1 &sipStrings_libserial[682]
#define sipNameNr_CHAR_SIZE_8 694
#define sipName_CHAR_SIZE_8 &sipStrings_libserial[694]
#define sipNameNr_CHAR_SIZE_7 706
#define sipName_CHAR_SIZE_7 &sipStrings_libserial[706]
#define sipNameNr_CHAR_SIZE_6 718
#define sipName_CHAR_SIZE_6 &sipStrings_libserial[718]
#define sipNameNr_CHAR_SIZE_5 730
#define sipName_CHAR_SIZE_5 &sipStrings_libserial[730]
#define sipNameNr_BAUD_460800 742
#define sipName_BAUD_460800 &sipStrings_libserial[742]
#define sipNameNr_BAUD_230400 754
#define sipName_BAUD_230400 &sipStrings_libserial[754]
#define sipNameNr_BAUD_115200 766
#define sipName_BAUD_115200 &sipStrings_libserial[766]
#define sipNameNr_std__string 778
#define sipName_std__string &sipStrings_libserial[778]
#define sipNameNr_logic_error 497
#define sipName_logic_error &sipStrings_libserial[497]
#define sipNameNr_OpenFailed 195
#define sipName_OpenFailed &sipStrings_libserial[195]
#define sipNameNr_PARITY_ODD 790
#define sipName_PARITY_ODD &sipStrings_libserial[790]
#define sipNameNr_BAUD_57600 801
#define sipName_BAUD_57600 &sipStrings_libserial[801]
#define sipNameNr_BAUD_38400 812
#define sipName_BAUD_38400 &sipStrings_libserial[812]
#define sipNameNr_BAUD_19200 823
#define sipName_BAUD_19200 &sipStrings_libserial[823]
#define sipNameNr_SerialPort 834
#define sipName_SerialPort &sipStrings_libserial[834]
#define sipNameNr_WriteByte 845
#define sipName_WriteByte &sipStrings_libserial[845]
#define sipNameNr_GetParity 855
#define sipName_GetParity &sipStrings_libserial[855]
#define sipNameNr_SetParity 865
#define sipName_SetParity &sipStrings_libserial[865]
#define sipNameNr_BAUD_9600 875
#define sipName_BAUD_9600 &sipStrings_libserial[875]
#define sipNameNr_BAUD_4800 885
#define sipName_BAUD_4800 &sipStrings_libserial[885]
#define sipNameNr_BAUD_2400 895
#define sipName_BAUD_2400 &sipStrings_libserial[895]
#define sipNameNr_BAUD_1800 905
#define sipName_BAUD_1800 &sipStrings_libserial[905]
#define sipNameNr_BAUD_1200 915
#define sipName_BAUD_1200 &sipStrings_libserial[915]
#define sipNameNr_exception 575
#define sipName_exception &sipStrings_libserial[575]
#define sipNameNr_libserial 925
#define sipName_libserial &sipStrings_libserial[925]
#define sipNameNr_ReadLine 935
#define sipName_ReadLine &sipStrings_libserial[935]
#define sipNameNr_ReadByte 944
#define sipName_ReadByte &sipStrings_libserial[944]
#define sipNameNr_StopBits 261
#define sipName_StopBits &sipStrings_libserial[261]
#define sipNameNr_BAUD_600 953
#define sipName_BAUD_600 &sipStrings_libserial[953]
#define sipNameNr_BAUD_300 962
#define sipName_BAUD_300 &sipStrings_libserial[962]
#define sipNameNr_BAUD_200 971
#define sipName_BAUD_200 &sipStrings_libserial[971]
#define sipNameNr_BAUD_150 980
#define sipName_BAUD_150 &sipStrings_libserial[980]
#define sipNameNr_BAUD_134 989
#define sipName_BAUD_134 &sipStrings_libserial[989]
#define sipNameNr_BAUD_110 998
#define sipName_BAUD_110 &sipStrings_libserial[998]
#define sipNameNr_BaudRate 23
#define sipName_BaudRate &sipStrings_libserial[23]
#define sipNameNr_NotOpen 323
#define sipName_NotOpen &sipStrings_libserial[323]
#define sipNameNr_BAUD_75 1007
#define sipName_BAUD_75 &sipStrings_libserial[1007]
#define sipNameNr_BAUD_50 1015
#define sipName_BAUD_50 &sipStrings_libserial[1015]
#define sipNameNr_GetDsr 1023
#define sipName_GetDsr &sipStrings_libserial[1023]
#define sipNameNr_GetCts 1030
#define sipName_GetCts &sipStrings_libserial[1030]
#define sipNameNr_GetRts 1037
#define sipName_GetRts &sipStrings_libserial[1037]
#define sipNameNr_SetRts 1044
#define sipName_SetRts &sipStrings_libserial[1044]
#define sipNameNr_GetDtr 1051
#define sipName_GetDtr &sipStrings_libserial[1051]
#define sipNameNr_SetDtr 1058
#define sipName_SetDtr &sipStrings_libserial[1058]
#define sipNameNr_IsOpen 1065
#define sipName_IsOpen &sipStrings_libserial[1065]
#define sipNameNr_Parity 343
#define sipName_Parity &sipStrings_libserial[343]
#define sipNameNr_string 783
#define sipName_string &sipStrings_libserial[783]
#define sipNameNr_Write 1072
#define sipName_Write &sipStrings_libserial[1072]
#define sipNameNr_Close 1078
#define sipName_Close &sipStrings_libserial[1078]
#define sipNameNr_Read 1084
#define sipName_Read &sipStrings_libserial[1084]
#define sipNameNr_Open 154
#define sipName_Open &sipStrings_libserial[154]
#define sipNameNr_what 1089
#define sipName_what &sipStrings_libserial[1089]
#define sipNameNr_std 1094
#define sipName_std &sipStrings_libserial[1094]

#define sipMalloc                   sipAPI_libserial->api_malloc
#define sipFree                     sipAPI_libserial->api_free
#define sipBuildResult              sipAPI_libserial->api_build_result
#define sipCallMethod               sipAPI_libserial->api_call_method
#define sipParseResult              sipAPI_libserial->api_parse_result
#define sipParseArgs                sipAPI_libserial->api_parse_args
#define sipParsePair                sipAPI_libserial->api_parse_pair
#define sipCommonDtor               sipAPI_libserial->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_libserial->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_libserial->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_libserial->api_convert_to_void_ptr
#define sipNoFunction               sipAPI_libserial->api_no_function
#define sipNoMethod                 sipAPI_libserial->api_no_method
#define sipAbstractMethod           sipAPI_libserial->api_abstract_method
#define sipBadClass                 sipAPI_libserial->api_bad_class
#define sipBadCatcherResult         sipAPI_libserial->api_bad_catcher_result
#define sipBadOperatorArg           sipAPI_libserial->api_bad_operator_arg
#define sipTrace                    sipAPI_libserial->api_trace
#define sipTransferBack             sipAPI_libserial->api_transfer_back
#define sipTransferTo               sipAPI_libserial->api_transfer_to
#define sipTransferBreak            sipAPI_libserial->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_libserial->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_libserial->api_wrapper_type
#define sipWrapperType_Type         sipAPI_libserial->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_libserial->api_voidptr_type
#define sipGetPyObject              sipAPI_libserial->api_get_pyobject
#define sipGetCppPtr                sipAPI_libserial->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_libserial->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_libserial->api_is_py_method
#define sipCallHook                 sipAPI_libserial->api_call_hook
#define sipStartThread              sipAPI_libserial->api_start_thread
#define sipEndThread                sipAPI_libserial->api_end_thread
#define sipConnectRx                sipAPI_libserial->api_connect_rx
#define sipDisconnectRx             sipAPI_libserial->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_libserial->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_libserial->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_libserial->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_libserial->api_add_type_instance
#define sipGetAddress               sipAPI_libserial->api_get_address
#define sipFreeSipslot              sipAPI_libserial->api_free_sipslot
#define sipSameSlot                 sipAPI_libserial->api_same_slot
#define sipPySlotExtend             sipAPI_libserial->api_pyslot_extend
#define sipConvertRx                sipAPI_libserial->api_convert_rx
#define sipAddDelayedDtor           sipAPI_libserial->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_libserial->api_can_convert_to_type
#define sipConvertToType            sipAPI_libserial->api_convert_to_type
#define sipForceConvertToType       sipAPI_libserial->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_libserial->api_can_convert_to_enum
#define sipReleaseType              sipAPI_libserial->api_release_type
#define sipConvertFromType          sipAPI_libserial->api_convert_from_type
#define sipConvertFromNewType       sipAPI_libserial->api_convert_from_new_type
#define sipConvertFromEnum          sipAPI_libserial->api_convert_from_enum
#define sipGetState                 sipAPI_libserial->api_get_state
#define sipLong_AsUnsignedLong      sipAPI_libserial->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_libserial->api_export_symbol
#define sipImportSymbol             sipAPI_libserial->api_import_symbol
#define sipFindType                 sipAPI_libserial->api_find_type
#define sipFindNamedEnum            sipAPI_libserial->api_find_named_enum
#define sipBytes_AsChar             sipAPI_libserial->api_bytes_as_char
#define sipBytes_AsString           sipAPI_libserial->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_libserial->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_libserial->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_libserial->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_libserial->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_libserial->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_libserial->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_libserial->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_libserial->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_libserial->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_libserial->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_libserial->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_libserial->api_invoke_slot
#define sipSaveSlot                 sipAPI_libserial->api_save_slot
#define sipClearAnySlotReference    sipAPI_libserial->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_libserial->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->type->td_cname)
#define sipDeprecated               sipAPI_libserial->api_deprecated
#define sipKeepReference            sipAPI_libserial->api_keep_reference
#define sipRegisterPyType           sipAPI_libserial->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_libserial->api_type_from_py_type_object
#define sipTypeScope                sipAPI_libserial->api_type_scope
#define sipResolveTypedef           sipAPI_libserial->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_libserial->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_libserial->api_is_api_enabled
#define sipExportModule             sipAPI_libserial->api_export_module
#define sipInitModule               sipAPI_libserial->api_init_module

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_libserial->api_map_string_to_class
#define sipMapIntToClass            sipAPI_libserial->api_map_int_to_class
#define sipFindClass                sipAPI_libserial->api_find_class
#define sipFindMappedType           sipAPI_libserial->api_find_mapped_type
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_libserial->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->type)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->type, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->type, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->type, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->type, (t))

/* The strings used by this module. */
extern const char sipStrings_libserial[];

#define sipType_std              sipModuleAPI_libserial.em_types[11]
#define sipClass_std             sipModuleAPI_libserial.em_types[11]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_libserial_std;

#define sipType_std_exception              sipModuleAPI_libserial.em_types[12]
#define sipClass_std_exception             sipModuleAPI_libserial.em_types[12]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_libserial_std_exception;

#define sipType_std_logic_error              sipModuleAPI_libserial.em_types[14]
#define sipClass_std_logic_error             sipModuleAPI_libserial.em_types[14]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_libserial_std_logic_error;

#define sipType_std_runtime_error              sipModuleAPI_libserial.em_types[15]
#define sipClass_std_runtime_error             sipModuleAPI_libserial.em_types[15]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_libserial_std_runtime_error;

#define sipType_std_invalid_argument              sipModuleAPI_libserial.em_types[13]
#define sipClass_std_invalid_argument             sipModuleAPI_libserial.em_types[13]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_libserial_std_invalid_argument;

#define sipType_SerialPort              sipModuleAPI_libserial.em_types[0]
#define sipClass_SerialPort             sipModuleAPI_libserial.em_types[0]->u.td_wrapper_type

#define sipType_SerialPort_FlowControl              sipModuleAPI_libserial.em_types[4]
#define sipEnum_SerialPort_FlowControl              sipModuleAPI_libserial.em_types[4]->u.td_py_type
#define sipType_SerialPort_Parity              sipModuleAPI_libserial.em_types[7]
#define sipEnum_SerialPort_Parity              sipModuleAPI_libserial.em_types[7]->u.td_py_type
#define sipType_SerialPort_StopBits              sipModuleAPI_libserial.em_types[9]
#define sipEnum_SerialPort_StopBits              sipModuleAPI_libserial.em_types[9]->u.td_py_type
#define sipType_SerialPort_CharacterSize              sipModuleAPI_libserial.em_types[3]
#define sipEnum_SerialPort_CharacterSize              sipModuleAPI_libserial.em_types[3]->u.td_py_type
#define sipType_SerialPort_BaudRate              sipModuleAPI_libserial.em_types[2]
#define sipEnum_SerialPort_BaudRate              sipModuleAPI_libserial.em_types[2]->u.td_py_type

extern sipClassTypeDef sipTypeDef_libserial_SerialPort;

#define sipType_SerialPort_NotOpen              sipModuleAPI_libserial.em_types[5]
#define sipClass_SerialPort_NotOpen             sipModuleAPI_libserial.em_types[5]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_libserial_SerialPort_NotOpen;

#define sipType_SerialPort_OpenFailed              sipModuleAPI_libserial.em_types[6]
#define sipClass_SerialPort_OpenFailed             sipModuleAPI_libserial.em_types[6]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_libserial_SerialPort_OpenFailed;

#define sipType_SerialPort_AlreadyOpen              sipModuleAPI_libserial.em_types[1]
#define sipClass_SerialPort_AlreadyOpen             sipModuleAPI_libserial.em_types[1]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_libserial_SerialPort_AlreadyOpen;

#define sipType_SerialPort_UnsupportedBaudRate              sipModuleAPI_libserial.em_types[10]
#define sipClass_SerialPort_UnsupportedBaudRate             sipModuleAPI_libserial.em_types[10]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_libserial_SerialPort_UnsupportedBaudRate;

#define sipType_SerialPort_ReadTimeout              sipModuleAPI_libserial.em_types[8]
#define sipClass_SerialPort_ReadTimeout             sipModuleAPI_libserial.em_types[8]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_libserial_SerialPort_ReadTimeout;

#define sipType_std_vector_1300      sipModuleAPI_libserial.em_types[19]

extern sipMappedTypeDef sipTypeDef_libserial_std_vector_1300;

#define sipType_std_vector_1900      sipModuleAPI_libserial.em_types[20]

extern sipMappedTypeDef sipTypeDef_libserial_std_vector_1900;

#define sipType_std_vector_1800      sipModuleAPI_libserial.em_types[18]

extern sipMappedTypeDef sipTypeDef_libserial_std_vector_1800;

#define sipType_std_vector_2400      sipModuleAPI_libserial.em_types[17]

extern sipMappedTypeDef sipTypeDef_libserial_std_vector_2400;

#define sipType_std_string      sipModuleAPI_libserial.em_types[16]

extern sipMappedTypeDef sipTypeDef_libserial_std_string;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_libserial;
extern sipExportedModuleDef sipModuleAPI_libserial;

#endif
