/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.9.1-snapshot-20091015 on Mon Nov 16 19:36:49 2009
 */

#include "sipAPIlibserial.h"

#line 5 "SerialPort.sip"
#include <SerialPort.h>
#line 12 "siplibserialSerialPortReadTimeout.cpp"



class sipSerialPort_ReadTimeout : public SerialPort::ReadTimeout
{
public:
    sipSerialPort_ReadTimeout();
    sipSerialPort_ReadTimeout(const SerialPort::ReadTimeout&);
    virtual ~sipSerialPort_ReadTimeout() throw();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    const char * what() const throw();

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipSerialPort_ReadTimeout(const sipSerialPort_ReadTimeout &);
    sipSerialPort_ReadTimeout &operator = (const sipSerialPort_ReadTimeout &);

    char sipPyMethods[1];
};

sipSerialPort_ReadTimeout::sipSerialPort_ReadTimeout(): SerialPort::ReadTimeout(), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipSerialPort_ReadTimeout::sipSerialPort_ReadTimeout(const SerialPort::ReadTimeout& a0): SerialPort::ReadTimeout(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipSerialPort_ReadTimeout::~sipSerialPort_ReadTimeout() throw()
{
    sipCommonDtor(sipPySelf);
}

const char * sipSerialPort_ReadTimeout::what() const throw()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[0]),sipPySelf,NULL,sipName_what);

    if (!meth)
        return std::runtime_error::what();

    extern const char * sipVH_libserial_0(sip_gilstate_t,PyObject *,int,sipSimpleWrapper *);

    return sipVH_libserial_0(sipGILState,meth,1,sipPySelf);
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_SerialPort_ReadTimeout(void *, const sipTypeDef *);}
static void *cast_SerialPort_ReadTimeout(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_SerialPort_ReadTimeout)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_std_runtime_error)->ctd_cast((std::runtime_error *)(SerialPort::ReadTimeout *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_SerialPort_ReadTimeout(void *, int);}
static void release_SerialPort_ReadTimeout(void *sipCppV,int state)
{
#line 105 "SerialPort.sip"
	        return ;
#line 93 "siplibserialSerialPortReadTimeout.cpp"

    if (state & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipSerialPort_ReadTimeout *>(sipCppV);
    else
        delete reinterpret_cast<SerialPort::ReadTimeout *>(sipCppV);
}


extern "C" {static void assign_SerialPort_ReadTimeout(void *, SIP_SSIZE_T, const void *);}
static void assign_SerialPort_ReadTimeout(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<SerialPort::ReadTimeout *>(sipDst)[sipDstIdx] = *reinterpret_cast<const SerialPort::ReadTimeout *>(sipSrc);
}


extern "C" {static void *array_SerialPort_ReadTimeout(SIP_SSIZE_T);}
static void *array_SerialPort_ReadTimeout(SIP_SSIZE_T sipNrElem)
{
    return new SerialPort::ReadTimeout[sipNrElem];
}


extern "C" {static void *copy_SerialPort_ReadTimeout(const void *, SIP_SSIZE_T);}
static void *copy_SerialPort_ReadTimeout(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new SerialPort::ReadTimeout(reinterpret_cast<const SerialPort::ReadTimeout *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_SerialPort_ReadTimeout(sipSimpleWrapper *);}
static void dealloc_SerialPort_ReadTimeout(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipSerialPort_ReadTimeout *>(sipSelf->u.cppPtr)->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_SerialPort_ReadTimeout(sipSelf->u.cppPtr,sipSelf->flags);
    }
}


extern "C" {static void *init_SerialPort_ReadTimeout(sipSimpleWrapper *, PyObject *, PyObject **, int *);}
static void *init_SerialPort_ReadTimeout(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject **, int *sipArgsParsed)
{
    sipSerialPort_ReadTimeout *sipCpp = 0;

    if (!sipCpp)
    {
        if (sipParseArgs(sipArgsParsed,sipArgs,""))
        {
            try
            {
            sipCpp = new sipSerialPort_ReadTimeout();
            }
            catch (...)
            {
                sipRaiseUnknownException();
                return NULL;
            }
        }
    }

    if (!sipCpp)
    {
        const SerialPort::ReadTimeout * a0;

        if (sipParseArgs(sipArgsParsed,sipArgs,"J9",sipType_SerialPort_ReadTimeout,&a0))
        {
            try
            {
            sipCpp = new sipSerialPort_ReadTimeout(*a0);
            }
            catch (...)
            {
                sipRaiseUnknownException();
                return NULL;
            }
        }
    }

    if (sipCpp)
        sipCpp->sipPySelf = sipSelf;

    return sipCpp;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_SerialPort_ReadTimeout[] = {{15, 255, 1}};


sipClassTypeDef sipTypeDef_libserial_SerialPort_ReadTimeout = {
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_SerialPort__ReadTimeout,
        {0}
    },
    {
        sipNameNr_ReadTimeout,
        {0, 255, 0},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    -1,
    -1,
    supers_SerialPort_ReadTimeout,
    0,
    init_SerialPort_ReadTimeout,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_SerialPort_ReadTimeout,
    assign_SerialPort_ReadTimeout,
    array_SerialPort_ReadTimeout,
    copy_SerialPort_ReadTimeout,
    release_SerialPort_ReadTimeout,
    cast_SerialPort_ReadTimeout,
    0,
    0,
    0
};
