/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.9.1-snapshot-20091015 on Mon Nov 16 19:36:49 2009
 */

#include "sipAPIlibserial.h"

#line 5 "SerialPort.sip"
#include <SerialPort.h>
#line 12 "siplibserialSerialPortAlreadyOpen.cpp"

#line 4 "string.sip"
#include <string>
#include <iostream>
#line 17 "siplibserialSerialPortAlreadyOpen.cpp"


class sipSerialPort_AlreadyOpen : public SerialPort::AlreadyOpen
{
public:
    sipSerialPort_AlreadyOpen(const std::string&);
    sipSerialPort_AlreadyOpen(const SerialPort::AlreadyOpen&);
    virtual ~sipSerialPort_AlreadyOpen() throw();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    const char * what() const throw();

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipSerialPort_AlreadyOpen(const sipSerialPort_AlreadyOpen &);
    sipSerialPort_AlreadyOpen &operator = (const sipSerialPort_AlreadyOpen &);

    char sipPyMethods[1];
};

sipSerialPort_AlreadyOpen::sipSerialPort_AlreadyOpen(const std::string& a0): SerialPort::AlreadyOpen(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipSerialPort_AlreadyOpen::sipSerialPort_AlreadyOpen(const SerialPort::AlreadyOpen& a0): SerialPort::AlreadyOpen(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipSerialPort_AlreadyOpen::~sipSerialPort_AlreadyOpen() throw()
{
    sipCommonDtor(sipPySelf);
}

const char * sipSerialPort_AlreadyOpen::what() const throw()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[0]),sipPySelf,NULL,sipName_what);

    if (!meth)
        return std::logic_error::what();

    extern const char * sipVH_libserial_0(sip_gilstate_t,PyObject *,int,sipSimpleWrapper *);

    return sipVH_libserial_0(sipGILState,meth,3,sipPySelf);
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_SerialPort_AlreadyOpen(void *, const sipTypeDef *);}
static void *cast_SerialPort_AlreadyOpen(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_SerialPort_AlreadyOpen)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_std_logic_error)->ctd_cast((std::logic_error *)(SerialPort::AlreadyOpen *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_SerialPort_AlreadyOpen(void *, int);}
static void release_SerialPort_AlreadyOpen(void *sipCppV,int state)
{
#line 85 "SerialPort.sip"
	        return ;
#line 97 "siplibserialSerialPortAlreadyOpen.cpp"

    if (state & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipSerialPort_AlreadyOpen *>(sipCppV);
    else
        delete reinterpret_cast<SerialPort::AlreadyOpen *>(sipCppV);
}


extern "C" {static void dealloc_SerialPort_AlreadyOpen(sipSimpleWrapper *);}
static void dealloc_SerialPort_AlreadyOpen(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipSerialPort_AlreadyOpen *>(sipSelf->u.cppPtr)->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_SerialPort_AlreadyOpen(sipSelf->u.cppPtr,sipSelf->flags);
    }
}


extern "C" {static void *init_SerialPort_AlreadyOpen(sipSimpleWrapper *, PyObject *, PyObject **, int *);}
static void *init_SerialPort_AlreadyOpen(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject **, int *sipArgsParsed)
{
    sipSerialPort_AlreadyOpen *sipCpp = 0;

    if (!sipCpp)
    {
        const std::string * a0;
        int a0State = 0;

        if (sipParseArgs(sipArgsParsed,sipArgs,"J1",sipType_std_string,&a0,&a0State))
        {
            try
            {
            sipCpp = new sipSerialPort_AlreadyOpen(*a0);
            }
            catch (...)
            {

            sipReleaseType(const_cast<std::string *>(a0),sipType_std_string,a0State);
                sipRaiseUnknownException();
                return NULL;
            }

            sipReleaseType(const_cast<std::string *>(a0),sipType_std_string,a0State);
        }
    }

    if (!sipCpp)
    {
        const SerialPort::AlreadyOpen * a0;

        if (sipParseArgs(sipArgsParsed,sipArgs,"J9",sipType_SerialPort_AlreadyOpen,&a0))
        {
            try
            {
            sipCpp = new sipSerialPort_AlreadyOpen(*a0);
            }
            catch (...)
            {
                sipRaiseUnknownException();
                return NULL;
            }
        }
    }

    if (sipCpp)
        sipCpp->sipPySelf = sipSelf;

    return sipCpp;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_SerialPort_AlreadyOpen[] = {{14, 255, 1}};


sipClassTypeDef sipTypeDef_libserial_SerialPort_AlreadyOpen = {
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_SerialPort__AlreadyOpen,
        {0}
    },
    {
        sipNameNr_AlreadyOpen,
        {0, 255, 0},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    -1,
    -1,
    supers_SerialPort_AlreadyOpen,
    0,
    init_SerialPort_AlreadyOpen,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_SerialPort_AlreadyOpen,
    0,
    0,
    0,
    release_SerialPort_AlreadyOpen,
    cast_SerialPort_AlreadyOpen,
    0,
    0,
    0
};
