/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.9.1-snapshot-20091015 on Mon Nov 16 19:36:49 2009
 */

#include "sipAPIlibserial.h"

#line 5 "SerialPort.sip"
#include <SerialPort.h>
#line 12 "siplibserialSerialPortUnsupportedBaudRate.cpp"

#line 4 "string.sip"
#include <string>
#include <iostream>
#line 17 "siplibserialSerialPortUnsupportedBaudRate.cpp"


class sipSerialPort_UnsupportedBaudRate : public SerialPort::UnsupportedBaudRate
{
public:
    sipSerialPort_UnsupportedBaudRate(const std::string&);
    sipSerialPort_UnsupportedBaudRate(const SerialPort::UnsupportedBaudRate&);
    virtual ~sipSerialPort_UnsupportedBaudRate() throw();

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    const char * what() const throw();

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipSerialPort_UnsupportedBaudRate(const sipSerialPort_UnsupportedBaudRate &);
    sipSerialPort_UnsupportedBaudRate &operator = (const sipSerialPort_UnsupportedBaudRate &);

    char sipPyMethods[1];
};

sipSerialPort_UnsupportedBaudRate::sipSerialPort_UnsupportedBaudRate(const std::string& a0): SerialPort::UnsupportedBaudRate(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipSerialPort_UnsupportedBaudRate::sipSerialPort_UnsupportedBaudRate(const SerialPort::UnsupportedBaudRate& a0): SerialPort::UnsupportedBaudRate(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipSerialPort_UnsupportedBaudRate::~sipSerialPort_UnsupportedBaudRate() throw()
{
    sipCommonDtor(sipPySelf);
}

const char * sipSerialPort_UnsupportedBaudRate::what() const throw()
{
    sip_gilstate_t sipGILState;
    PyObject *meth;

    meth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[0]),sipPySelf,NULL,sipName_what);

    if (!meth)
        return std::runtime_error::what();

    extern const char * sipVH_libserial_0(sip_gilstate_t,PyObject *,int,sipSimpleWrapper *);

    return sipVH_libserial_0(sipGILState,meth,2,sipPySelf);
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_SerialPort_UnsupportedBaudRate(void *, const sipTypeDef *);}
static void *cast_SerialPort_UnsupportedBaudRate(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_SerialPort_UnsupportedBaudRate)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_std_runtime_error)->ctd_cast((std::runtime_error *)(SerialPort::UnsupportedBaudRate *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_SerialPort_UnsupportedBaudRate(void *, int);}
static void release_SerialPort_UnsupportedBaudRate(void *sipCppV,int state)
{
#line 95 "SerialPort.sip"
	        return ;
#line 97 "siplibserialSerialPortUnsupportedBaudRate.cpp"

    if (state & SIP_DERIVED_CLASS)
        delete reinterpret_cast<sipSerialPort_UnsupportedBaudRate *>(sipCppV);
    else
        delete reinterpret_cast<SerialPort::UnsupportedBaudRate *>(sipCppV);
}


extern "C" {static void dealloc_SerialPort_UnsupportedBaudRate(sipSimpleWrapper *);}
static void dealloc_SerialPort_UnsupportedBaudRate(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipSerialPort_UnsupportedBaudRate *>(sipSelf->u.cppPtr)->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_SerialPort_UnsupportedBaudRate(sipSelf->u.cppPtr,sipSelf->flags);
    }
}


extern "C" {static void *init_SerialPort_UnsupportedBaudRate(sipSimpleWrapper *, PyObject *, PyObject **, int *);}
static void *init_SerialPort_UnsupportedBaudRate(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject **, int *sipArgsParsed)
{
    sipSerialPort_UnsupportedBaudRate *sipCpp = 0;

    if (!sipCpp)
    {
        const std::string * a0;
        int a0State = 0;

        if (sipParseArgs(sipArgsParsed,sipArgs,"J1",sipType_std_string,&a0,&a0State))
        {
            try
            {
            sipCpp = new sipSerialPort_UnsupportedBaudRate(*a0);
            }
            catch (...)
            {

            sipReleaseType(const_cast<std::string *>(a0),sipType_std_string,a0State);
                sipRaiseUnknownException();
                return NULL;
            }

            sipReleaseType(const_cast<std::string *>(a0),sipType_std_string,a0State);
        }
    }

    if (!sipCpp)
    {
        const SerialPort::UnsupportedBaudRate * a0;

        if (sipParseArgs(sipArgsParsed,sipArgs,"J9",sipType_SerialPort_UnsupportedBaudRate,&a0))
        {
            try
            {
            sipCpp = new sipSerialPort_UnsupportedBaudRate(*a0);
            }
            catch (...)
            {
                sipRaiseUnknownException();
                return NULL;
            }
        }
    }

    if (sipCpp)
        sipCpp->sipPySelf = sipSelf;

    return sipCpp;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_SerialPort_UnsupportedBaudRate[] = {{15, 255, 1}};


sipClassTypeDef sipTypeDef_libserial_SerialPort_UnsupportedBaudRate = {
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_SerialPort__UnsupportedBaudRate,
        {0}
    },
    {
        sipNameNr_UnsupportedBaudRate,
        {0, 255, 0},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    -1,
    -1,
    supers_SerialPort_UnsupportedBaudRate,
    0,
    init_SerialPort_UnsupportedBaudRate,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_SerialPort_UnsupportedBaudRate,
    0,
    0,
    0,
    release_SerialPort_UnsupportedBaudRate,
    cast_SerialPort_UnsupportedBaudRate,
    0,
    0,
    0
};
