/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.9.1-snapshot-20091015 on Mon Nov 16 19:36:49 2009
 */

#include "sipAPIlibserial.h"

#line 112 "vector.sip"
#include <vector>
#line 12 "siplibserialstdvector2400.cpp"



extern "C" {static void assign_std_vector_2400(void *, SIP_SSIZE_T, const void *);}
static void assign_std_vector_2400(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<std::vector<double> *>(sipDst)[sipDstIdx] = *reinterpret_cast<const std::vector<double> *>(sipSrc);
}


extern "C" {static void *array_std_vector_2400(SIP_SSIZE_T);}
static void *array_std_vector_2400(SIP_SSIZE_T sipNrElem)
{
    return new std::vector<double>[sipNrElem];
}


extern "C" {static void *copy_std_vector_2400(const void *, SIP_SSIZE_T);}
static void *copy_std_vector_2400(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new std::vector<double>(reinterpret_cast<const std::vector<double> *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_std_vector_2400(void *, int);}
static void release_std_vector_2400(void *ptr, int)
{
    delete reinterpret_cast<std::vector<double> *>(ptr);
}



extern "C" {static int convertTo_std_vector_2400(PyObject *, void **, int *, PyObject *);}
static int convertTo_std_vector_2400(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    std::vector<double> **sipCppPtr = reinterpret_cast<std::vector<double> **>(sipCppPtrV);

#line 135 "vector.sip"
    // Check if type is compatible
    if (sipIsErr == NULL)
    {
        // Must be any iterable
        PyObject *i = PyObject_GetIter(sipPy);
        bool iterable = (i != NULL);
        Py_XDECREF(i);
        return iterable;
    }

    // Iterate over the object
    PyObject *iterator = PyObject_GetIter(sipPy);
    PyObject *item;

    // Maximum number of elements
    int len = PyObject_Size(sipPy);
    std::vector<double> *V = new std::vector<double>();
    V->reserve(len);

    if (len)
    {
        while ((item = PyIter_Next(iterator)))
        {
            if (!PyNumber_Check(item))
            {
                PyErr_Format(PyExc_TypeError, "object in iterable is not a number");
                *sipIsErr = 1;
                break;
            }

            PyObject *f = PyNumber_Float(item);
            V->push_back(PyFloat_AsDouble(f));

            Py_DECREF(f);
            Py_DECREF(item);
        }

        Py_DECREF(iterator);

        if (*sipIsErr)
        {
            delete V;
            return 0;
        }
    }

    *sipCppPtr = V;
    return sipGetState(sipTransferObj);
#line 100 "siplibserialstdvector2400.cpp"
}


extern "C" {static PyObject *convertFrom_std_vector_2400(void *, PyObject *);}
static PyObject *convertFrom_std_vector_2400(void *sipCppV,PyObject *)
{
   std::vector<double> *sipCpp = reinterpret_cast<std::vector<double> *>(sipCppV);

#line 116 "vector.sip"
    PyObject *l;

    // Create the Python list of the correct length.
    if ((l = PyList_New(sipCpp -> size())) == NULL)
        return NULL;

    // Go through each element in the C++ instance and convert it to a
    // wrapped object.
    for (int i = 0; i < (int)sipCpp -> size(); ++i)
    {
        // Add the wrapper to the list.
        PyList_SET_ITEM(l, i, PyFloat_FromDouble(sipCpp -> at(i)));
    }

    // Return the Python list.
    return l;
#line 126 "siplibserialstdvector2400.cpp"
}


sipMappedTypeDef sipTypeDef_libserial_std_vector_2400 = {
    {
        -1,
        0,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_291,
        {0}
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_std_vector_2400,
    array_std_vector_2400,
    copy_std_vector_2400,
    release_std_vector_2400,
    convertTo_std_vector_2400,
    convertFrom_std_vector_2400
};
