######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 11 12:29:30 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CXXFLAGS += -mfpu=neon -ftree-vectorize -flax-vector-conversions

# Input
HEADERS += thread.h
SOURCES += camera.cpp thread.cpp
