######################################################################
# Automatically generated by qmake (2.01a) ? 11? 10 12:14:17 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += cachemodel.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += cachemodel.cpp main.cpp mainwindow.cpp
